---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- krb5-server/krb5-server.yaml
configMapGenerator:
- name: krb5-script
  files:
  - krb5-server/create-db.sh
  options:
    disableNameSuffixHash: true
...
