---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - krb5-server/krb5-server.yaml
  - scm/scm-0.yaml
  - scm/scm-1.yaml
  - scm/scm-2.yaml
  - om/om-0.yaml
  - om/om-1.yaml
  - om/om-2.yaml
  - datanode/dn-0.yaml
  - datanode/dn-1.yaml
  - datanode/dn-2.yaml
configMapGenerator:
  - name: keytabs
    files:
      - security/HTTP.keytab
      - security/SCM.keytab
      - security/OM.keytab
      - security/HDDS.keytab
    options:
      disableNameSuffixHash: true
  - name: krb5-script
    files:
      - krb5-server/create-db.sh
    options:
      disableNameSuffixHash: true
  - name: scm-script
    files:
      - scm/bootstrap-scm.sh
    options:
      disableNameSuffixHash: true
  - name: om-script
    files:
      - om/bootstrap-om.sh
    options:
      disableNameSuffixHash: true
...
