---
- hosts: localhost
  vars:
    ansible_connection: local
    self_signed_rootca_name: 'Fake CA'
    self_signed_ca_host: root-ca.example.com
    self_signed_domain:
      - scm-0.scm-0.default.svc.cluster.local
      - scm-1.scm-1.default.svc.cluster.local
      - scm-2.scm-2.default.svc.cluster.local
      - om-0.om-0.default.svc.cluster.local
      - om-1.om-1.default.svc.cluster.local
      - om-2.om-2.default.svc.cluster.local
      - dn-0.dn-0.default.svc.cluster.local
      - dn-1.dn-1.default.svc.cluster.local
      - dn-2.dn-2.default.svc.cluster.local
      - recon.recon.default.svc.cluster.local
    secret:
      privatekey:
        passphrase: changeit
      keystore:
        pass: changeit
    certs_deploy:
      - fqdn: scm-0.scm-0.default.svc.cluster.local
        dest: scm/hostpath/scm0/localcerts
      - fqdn: scm-1.scm-1.default.svc.cluster.local
        dest: scm/hostpath/scm1/localcerts
      - fqdn: scm-2.scm-2.default.svc.cluster.local
        dest: scm/hostpath/scm2/localcerts
      - fqdn: om-0.om-0.default.svc.cluster.local
        dest: om/hostpath/om0/localcerts
      - fqdn: om-1.om-1.default.svc.cluster.local
        dest: om/hostpath/om1/localcerts
      - fqdn: om-2.om-2.default.svc.cluster.local
        dest: om/hostpath/om2/localcerts
      - fqdn: dn-0.dn-0.default.svc.cluster.local
        dest: datanode/hostpath/dn0/localcerts
      - fqdn: dn-1.dn-1.default.svc.cluster.local
        dest: datanode/hostpath/dn1/localcerts
      - fqdn: dn-2.dn-2.default.svc.cluster.local
        dest: datanode/hostpath/dn2/localcerts
      - fqdn: recon.recon.default.svc.cluster.local
        dest: recon/hostpath/localcerts
  roles:
    - role: self_signed_certificate
      tags:
        - generate
    - role: java_certs
      tags:
        - deploy
    - role: deploy_certs
      tags:
        - deploy
  become: no
...
