---
apiVersion: v1
kind: Service
metadata:
  name: dn-2
  labels:
    app: ozone
    component: dn-2
spec:
  clusterIP: None
  ports:
    - port: 9856
      name: ratis-server
    - port: 9857
      name: ratis-admin
    - port: 9858
      name: ratis-ipc
    - port: 9859
      name: container-ipc
    - port: 9882
      name: http-address
    - port: 9883
      name: https-address
  selector:
    app: ozone
    component: dn-2
---
apiVersion: v1
kind: Pod
metadata:
  name: dn-2
  labels:
    app: ozone
    component: dn-2
spec:
  hostname: dn-2
  subdomain: dn-2
  setHostnameAsFQDN: true
  nodeSelector:
    kubernetes.io/hostname: ode-dn2
  containers:
    - name: dn
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      args:
        ["ozone", "datanode"]
      ports:
        - containerPort: 9856
          name: ratis-server
        - containerPort: 9857
          name: ratis-admin
        - containerPort: 9858
          name: ratis-ipc
        - containerPort: 9859
          name: container-ipc
        - containerPort: 9882
          name: http-address
        - containerPort: 9883
          name: https-address
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-datanode-dn-2.log
  initContainers:
    - name: wait
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod 777 /var/log/ozone
          chmod 777 /data
          echo 'waiting for any of scm-[0-2].default.svc.cluster.local be ready'
          while :; do
              nslookup scm-0.default.svc.cluster.local
              if [ $? -eq 0 ]; then break; fi
              nslookup scm-1.default.svc.cluster.local
              if [ $? -eq 0 ]; then break; fi
              nslookup scm-2.default.svc.cluster.local
              if [ $? -eq 0 ]; then break; fi
              sleep 5
          done
          echo 'waiting for any of scm-[0-2]:9861 (scm datanode port) be ready'
          while :; do
              nc -z -v scm-0 9861
              if [ $? -eq 0 ]; then break; fi
              nc -z -v scm-1 9861
              if [ $? -eq 0 ]; then break; fi
              nc -z -v scm-2 9861
              if [ $? -eq 0 ]; then break; fi
              sleep 5
          done
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /data
          name: ozone-data
          subPath: data
  volumes:
    - name: ozone-data
      hostPath:
        path: /volumes/dn
        type: Directory
    - name: keytabs
      configMap:
        name: keytabs
...
