---
apiVersion: v1
kind: Service
metadata:
  name: om-2
  labels:
    app: ozone
    component: om-2
spec:
  clusterIP: None
  ports:
    - port: 9862
      name: client
    - port: 9872
      name: ratis
    - port: 9874
      name: http-address
    - port: 9875
      name: https-address
  selector:
    app: ozone
    component: om-2
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Pod
metadata:
  name: om-2
  labels:
    app: ozone
    component: om-2
spec:
  hostname: om-2
  subdomain: om-2
  setHostnameAsFQDN: true
  nodeSelector:
    kubernetes.io/hostname: ode-om2
  containers:
    - name: om
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      args:
        ["ozone", "om"]
      ports:
        - containerPort: 9862
          name: client
        - containerPort: 9872
          name: ratis
        - containerPort: 9874
          name: http-address
        - containerPort: 9875
          name: https-address
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-om-om-2.log
  initContainers:
    - name: wait
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod 777 /var/log/ozone
          chmod 777 /data
          for i in 0 1; do
              until nslookup om-${i}.default.svc.cluster.local; do
                  echo waiting for om-${i}.default.svc.cluster.local
                  sleep 2
              done
          done
          echo 'waiting for any of scm-[0-2]:9861 (scm datanode port) be ready'
          while :; do
              nc -z -v scm-0 9861
              if [ $? -eq 0 ]; then break; fi
              nc -z -v scm-1 9861
              if [ $? -eq 0 ]; then break; fi
              nc -z -v scm-2 9861
              if [ $? -eq 0 ]; then break; fi
              sleep 5
          done
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /data
          name: ozone-data
          subPath: data
    - name: init
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      command: ["/script/bootstrap-om.sh"]
      ports:
        - containerPort: 9862
          name: client
        - containerPort: 9872
          name: ratis
        - containerPort: 9874
          name: http-address
        - containerPort: 9875
          name: https-address
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /script
          name: om-script
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-om-om-2.log
  volumes:
    - name: ozone-data
      hostPath:
        path: /volumes/om
        type: Directory
    - name: om-script
      configMap:
        name: om-script
        defaultMode: 0744
    - name: keytabs
      configMap:
        name: keytabs
...
