---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb5-client
spec:
  selector:
    matchLabels:
      app: krb5-client
  template:
    metadata:
      labels:
        app: krb5-client
    spec:
      containers:
        - name: krb5-client
          image: pfnmaru/krb5-client
          imagePullPolicy: IfNotPresent
...
