---
apiVersion: v1
kind: Service
metadata:
  name: ode-kerberos
  labels:
    app: krb5-server
spec:
  ports:
    - port: 88
      protocol: UDP
      name: kerberos
    - port: 750
      protocol: UDP
      name: kerberos-sec
  selector:
    app: krb5-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb5-server
spec:
  selector:
    matchLabels:
      app: krb5-server
  template:
    metadata:
      labels:
        app: krb5-server
    spec:
      containers:
        - name: krb5-server
          image: pfnmaru/krb5-server
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/log/krb5kdc
              name: kdc-data
              subPath: log.krb5kdc
            - mountPath: /var/lib/krb5kdc
              name: kdc-data
              subPath: lib.krb5kdc
      initContainers:
         - name: krb5-server-init
           image: pfnmaru/krb5-server
           imagePullPolicy: IfNotPresent
           env:
             - name: KDB5_MASTERKEY
               value: "PLEASE_CHANGE_ME"
           command: ["/script/create-db.sh"]
           volumeMounts:
             - mountPath: /var/log/krb5kdc
               name: kdc-data
               subPath: log.krb5kdc
             - mountPath: /var/lib/krb5kdc
               name: kdc-data
               subPath: lib.krb5kdc
             - mountPath: /script
               name: krb5-script
      nodeSelector:
        kubernetes.io/hostname: ode-kerberos
      volumes:
        - name: kdc-data
          hostPath:
            path: /volumes/krb5-server
            type: Directory
        - name: krb5-script
          configMap:
            name: krb5-script
            defaultMode: 0744
...
