---
- name: set certificate task vars
  ansible.builtin.set_fact:
    self_signed_ca_host: '{{ self_signed_ca_host | default(False) }}'
    local_dir: ./security

- name: copy certificate
  ansible.builtin.copy:
    src: '{{ local_dir }}/{{ item.fqdn }}.cert'
    dest: '{{ item.dest }}/{{ item.fqdn }}.cert'
    mode: '0644'
  delegate_to: localhost
  loop:
    '{{ certs_deploy }}'

- name: create a link to the certificate
  ansible.builtin.file:
    src: '{{ item.fqdn }}.cert'
    dest: '{{ item.dest }}/server.cert'
    state: link
  delegate_to: localhost
  loop:
    '{{ certs_deploy }}'

- name: copy truststore
  ansible.builtin.copy:
    src: '{{ local_dir }}/jssecacerts'
    dest: '{{ item.dest }}/jssecacerts'
    mode: '0644'
  delegate_to: localhost
  loop:
    '{{ certs_deploy }}'

- name: create a keystore
  community.general.java_keystore:
    name: '{{ item.fqdn }}'
    dest: '{{ item.dest }}/server.jks'
    certificate_path: '{{ local_dir }}/{{ item.fqdn }}.cert'
    private_key_path: '{{ local_dir }}/{{ item.fqdn }}.key'
    private_key_passphrase: '{{ secret.privatekey.passphrase }}'
    password: '{{ secret.keystore.pass }}'
    keystore_type: jks
  delegate_to: localhost
  loop:
    '{{ certs_deploy }}'
...
