---
apiVersion: v1
kind: Service
metadata:
  name: recon
  labels:
    app: ozone
    component: recon
spec:
  ports:
    - port: 9888
      name: http-address
    - port: 9889
      name: https-address
    - port: 9891
      name: datanode
  selector:
    app: ozone
    component: recon
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Pod
metadata:
  name: recon
  labels:
    app: ozone
    component: recon
spec:
  hostname: recon
  subdomain: recon
  setHostnameAsFQDN: true
  nodeSelector:
    kubernetes.io/hostname: ode-recon
  containers:
    - name: recon
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      args:
        ["ozone", "recon"]
      ports:
        - containerPort: 9888
          name: http-address
        - containerPort: 9889
          name: https-port
        - containerPort: 9891
          name: datanode
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-recon-recon.log
  initContainers:
    - name: wait
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod 777 /var/log/ozone
          chmod 777 /data
          until nslookup recon.default.svc.cluster.local; do
              echo 'waiting for recon.default.svc.cluster.local'
              sleep 2
          done
          echo 'waiting for MIT KDC be ready'
          while :; do
              nc -z -v ode-kerberos 88
              if [ $? -eq 0 ]; then break; fi
              nc -z -v ode-kerberos 750
              if [ $? -eq 0 ]; then break; fi
              sleep 5
          done
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /data
          name: ozone-data
          subPath: data
  volumes:
    - name: ozone-data
      hostPath:
        path: /volumes/recon
        type: Directory
    - name: keytabs
      configMap:
        name: keytabs
...
