---
apiVersion: v1
kind: Service
metadata:
  name: scm-1
  labels:
    app: ozone
    component: scm-1
spec:
  clusterIP: None
  ports:
    - port: 9860
      name: client
    - port: 9861
      name: datanode
    - port: 9863
      name: block-client
    - port: 9876
      name: http-address
    - port: 9894
      name: ratis
    - port: 9895
      name: grpc
    - port: 9961
      name: security
  selector:
    app: ozone
    component: scm-1
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Pod
metadata:
  name: scm-1
  labels:
    app: ozone
    component: scm-1
spec:
  hostname: scm-1
  subdomain: scm-1
  setHostnameAsFQDN: true
  nodeSelector:
    kubernetes.io/hostname: ode-scm1
  containers:
    - name: scm
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      args:
        ["ozone", "scm"]
      ports:
        - containerPort: 9860
          name: client
        - containerPort: 9861
          name: datanode
        - containerPort: 9863
          name: block-client
        - containerPort: 9876
          name: http-address
        - containerPort: 9894
          name: ratis
        - containerPort: 9895
          name: grpc
        - containerPort: 9961
          name: security
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-scm-scm-1.log
  initContainers:
    - name: wait
      image: alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          chmod 777 /var/log/ozone
          chmod 777 /data
          for i in 0 2; do
              until nslookup scm-${i}.default.svc.cluster.local; do
                  echo waiting for scm-${i}.default.svc.cluster.local
                  sleep 2
              done
          done
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /data
          name: ozone-data
          subPath: data
    - name: init
      image: pfnmaru/ozone-runner
      imagePullPolicy: IfNotPresent
      command: ["/script/bootstrap-scm.sh"]
      ports:
        - containerPort: 9860
          name: client
        - containerPort: 9861
          name: datanode
        - containerPort: 9863
          name: block-client
        - containerPort: 9876
          name: http-address
        - containerPort: 9894
          name: ratis
        - containerPort: 9895
          name: grpc
        - containerPort: 9961
          name: security
      volumeMounts:
        - mountPath: /var/log/ozone
          name: ozone-data
          subPath: log.ozone
        - mountPath: /opt/ozone/etc/hadoop
          name: ozone-data
          subPath: etc.hadoop
        - mountPath: /data
          name: ozone-data
          subPath: data
        - mountPath: /script
          name: scm-script
        - mountPath: /etc/security/keytabs
          name: keytabs
        - mountPath: /etc/ssl/localcerts
          name: ozone-data
          subPath: localcerts
      env:
        - name: OZONE_LOG_DIR
          value: /var/log/ozone
        - name: OZONE_ROOT_LOGGER
          value: "INFO,RFA"
        - name: OZONE_LOGFILE
          value: ozone-ozone-scm-scm-1.log
  volumes:
    - name: ozone-data
      hostPath:
        path: /volumes/scm
        type: Directory
    - name: scm-script
      configMap:
        name: scm-script
        defaultMode: 0744
    - name: keytabs
      configMap:
        name: keytabs
...
