---
apiVersion: v1
kind: Service
metadata:
  name: scm
  labels:
    app: ozone
spec:
  clusterIP: None
  ports:
    - port: 9876
      name: ui
  selector:
    app: ozone
    component: scm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scm
  labels:
    app.kubernetes.io/component: ozone
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: scm
  replicas: 3
  template:
    metadata:
      labels:
        app: ozone
        component: scm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: ode/nodetype
                    operator: In
                    values:
                      - scm
      containers:
        - name: scm
          image: pfnmaru/ozone-runner
          imagePullPolicy: IfNotPresent
          args:
            ["ozone", "scm"]
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
            - mountPath: /opt/hadoop/etc/hadoop
              name: scm-config
      initContainers:
        - name: scm-init-path
          image: alpine
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - chmod 777 /var/log/hadoop
            - chmod 777 /data
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
        - name: scm-init
          image: pfnmaru/ozone-runner
          imagePullPolicy: IfNotPresent
          command: ["/script/bootstrap-scm.sh"]
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
            - mountPath: /script
              name: scm-script
            - mountPath: /opt/hadoop/etc/hadoop
              name: scm-config
      volumes:
        - name: ozone-data
          hostPath:
            path: /volumes/scm
            type: Directory
        - name: scm-script
          configMap:
            name: scm-script
            defaultMode: 0744
        - name: scm-config
          configMap:
            name: scm-config
...
