---
apiVersion: v1
kind: Service
metadata:
  name: scm
  labels:
    app: ozone
spec:
  clusterIP: None
  ports:
    - port: 9863
      name: block-client
    - port: 9876
      name: http-address
  selector:
    app: ozone
    component: scm
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scm
  labels:
    app.kubernetes.io/component: ozone
spec:
  serviceName: scm
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: ozone
      component: scm
  template:
    metadata:
      labels:
        app: ozone
        component: scm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: ode/nodetype
                    operator: In
                    values:
                      - scm
      containers:
        - name: scm
          image: pfnmaru/ozone-runner
          imagePullPolicy: IfNotPresent
          args:
            ["ozone", "scm"]
          ports:
            - containerPort: 9863
              name: block-client
            - containerPort: 9876
              name: http-address
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /opt/hadoop/etc/hadoop
              name: ozone-data
              subPath: etc.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
      initContainers:
        - name: scm-init-path
          image: alpine
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              chmod 777 /var/log/hadoop
              chmod 777 /data
              for i in $(seq 0 2); do
                  until nslookup scm-${i}.scm.default.svc.cluster.local; do
                      echo waiting for scm-${i}.scm.default.svc.cluster.local
                      sleep 2
                  done
              done
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
        - name: scm-init
          image: pfnmaru/ozone-runner
          imagePullPolicy: IfNotPresent
          command: ["/script/bootstrap-scm.sh"]
          ports:
            - containerPort: 9863
              name: block-client
            - containerPort: 9876
              name: http-address
          volumeMounts:
            - mountPath: /var/log/hadoop
              name: ozone-data
              subPath: log.hadoop
            - mountPath: /opt/hadoop/etc/hadoop
              name: ozone-data
              subPath: etc.hadoop
            - mountPath: /data
              name: ozone-data
              subPath: data
            - mountPath: /script
              name: scm-script
      volumes:
        - name: ozone-data
          hostPath:
            path: /volumes/scm
            type: Directory
        - name: scm-script
          configMap:
            name: scm-script
            defaultMode: 0744
...
